name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build ZMK firmware
        uses: zmkfirmware/zmk-build-arm@main
        with:
          build-args: "-p -DZMK_CONFIG=${GITHUB_WORKSPACE}/config"

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            build/**/*.uf2
